### ISSUE TITLE
client/cache: 实现延迟双删模式

### ISSUE THREAD

**Issue by flycash** [ecodeclub/beego#3]
我在补充内容里面讲过延迟双删是如何实现的。

现在要求你在 client/cache 里面实现延迟双删机制。

参考 #2 和已有的 WriteThroughCache，你需要提供单元测试，保证代码质量。

**Comment by Stone-afk** [comment]
11111 明哥这个我来

**Comment by Stone-afk** [comment]
11111

**Comment by Stone-afk** [comment]
Is the delay asynchronous or synchronous? If asynchronous, what should I do if the deletion fails? Should I try again
